services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    BinSoul\Symfony\Bundle\Website\Repository\:
        resource: '../../Repository/*'
        public: true

    BinSoul\Symfony\Bundle\Website\EventListener\:
        resource: '../../EventListener/*'
        tags: ['kernel.event_subscriber']

    BinSoul\Symfony\Bundle\Website\EventListener\TablePrefixListener:
        public: true
