services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    BinSoul\Symfony\Bundle\Website\Repository\:
        resource: '../../Repository/*'
        public: true
